### ISSUE TITLE
Novas funcionalidades do losses_tools.py

### ISSUE THREAD

**Issue by JonasVil** [felipemarkson/dssdata#37]
Acrescentar funções e/ou agregar mais sobre as perdas relacionadas as componentes do tipo PD ao losses_tool.py. Por enquanto são apresentadas as perdas totais de todos os elementos do tipo PD, é interessante apresentar a contribuição de cada elemento para a composição dessa perda total.

Obs: Os capacitores aparecem como um elemento PD, mas durante o cálculo das perdas totais do circuito não são levados em cosideração.

**Comment by felipemarkson** [comment]
Acredito que deve-se realizar uma subdivisão melhor das responsabilidades do get_total_pd_elements_losses() criando funções auxiliares.

**Comment by felipemarkson** [comment]
Acredito que falte a criação de uma função que retorne as perdas individuais de cada PD element

**Comment by felipemarkson** [comment]
O PR #35 Fecha esta issue.
