### ISSUE TITLE
Método para obter as perdas totais do sistema.

### ISSUE THREAD

**Issue by felipemarkson** [felipemarkson/dssdata#9]
# Funcionalidade de retorno de perdas

## Como chamar a funcionalidade?
Precisa ser definido se a funcionalidade será um método ou um atributo do sistema. Eu acredito que pode ser um método.

## Estrutura de dados? 
Futuramente será implementado a funcionalidade de time-series. A funcionalidade deve ter uma estrutura de dados que possamos, no futuro, incluir no padrão DataFrame.

## Quais informações terão no retorno da funcionalidade?
O OpendssDirect possui os métodos :
- Circuit.LineLosses() : Este método retorna as perdas de todas as linhas.
- Circuit.Losses(): Este método retorna as perdas de todas as linhas com as perdas de outros dispositivos, como DG e Storage e etc...

Qual utilizar? englobar perdas de outros dispositivos?

**Comment by JonasVil** [comment]
**Quais informações terão no retorno da funcionalidade?**

- Fazer função com a possibilidade de retornar DataFrame com os dados de perdas para cada uma das linhas;
- Fazer função com a possbilidade de retornar informação de perdas para uma linha ou elemento (PD?) específico; 
- Identificar outras possíveis necessidades.

**Comment by felipemarkson** [comment]
As perdas de cada linha já estão implementadas no line_tools.py. Talvez o escopo dessas funções possam ser sempre retorno de dados totais.
Como "all_losses_lines" ou "all_losses_pd"

**Comment by JonasVil** [comment]
Acredito que apesar de já existir uma forma de se obter tais perdas, acredito ser necessário que exista uma forma possível de se obter as perdas de cada um dos elementos sem que exista a necessidade de fazer a aquisição de todos os outros elementos presentes no line_tools.py. Acredito que em uma simulação que envolve processo iterativo isso poderia vir a calhar.

**Comment by felipemarkson** [comment]
Então seria bom, utilizar um retorno parecido com como é feito com as linhas.
Um DataFrame com mais informações além de apenas perdas, para cada classe de eemento.

**Comment by JonasVil** [comment]
Quais informações você acredita serem pertinentes?

**Comment by felipemarkson** [comment]
O escopo do projeto é ser um agregador que retorna informações organizadas, solicitar apenas as perdas de um elemento pode ser feito através do SystemClass.dss.ElementCkt.Losses().

**Comment by felipemarkson** [comment]
Acredito que seria viável a criação de outra issue para discutimos essas informações.
Nesta ficaremos apenas com o escopo de criação de um tools para perdas totais do sistema.
